on:
  push:
    branches:
      - master
name: Deployment
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    
    - name: Sync new changes
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.server_destination }}
        port: ${{ secrets.port_destination }}
        username: ${{ secrets.username_access }}
        password: ${{ secrets.password_access }}
        server-dir: ${{ secrets.path_target }}
