on:
  push:
    branches-ignore:
      - master
name: Run on branch non "master"
jobs:
  web-deploy:
    name: Process to testing
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Sync new changes
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.SLAVE_SERVER }}
        username: ${{ secrets.SLAVE_USERNAME }}
        password: ${{ secrets.SLAVE_PASSWORD }}
        port: ${{ secrets.DEFAULT_PORT }}
        protocol: ftp
        server-dir: ${{ secrets.SLAVE_PATH }}
        exclude: |
          **/.git*
          **/.git*/**
        dry-run: true
