name: Run on branch "master"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Process to delivery
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    
    - name: Sync new changes
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.MASTER_SERVER }}
        username: ${{ secrets.MASTER_USERNAME }}
        password: ${{ secrets.MASTER_PASSWORD }}
        port: ${{ secrets.DEFAULT_PORT }}
        protocol: ftp
        server-dir: ${{ secrets.MASTER_PATH }}
        exclude: |
          **/.git*
          **/.git*/**
